era5:
  germany:
    outdir: data/raw/era5/ERA5_Germany
    start_year: 2004
    end_year: 2024
    variables_all:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 100m_u_component_of_wind
      - 100m_v_component_of_wind
      - 2m_temperature
      - surface_pressure
      - 2m_dewpoint_temperature
      - forecast_surface_roughness
      - friction_velocity

  points:
    outdir_root: data/raw/era5
    buffer_deg: 0.25

    core_variables:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 100m_u_component_of_wind
      - 100m_v_component_of_wind
      - 2m_temperature
      - surface_pressure
      - 2m_dewpoint_temperature

    roughness_variables:
      - forecast_surface_roughness
      - friction_velocity

    sites:
      Loegtved:
        lat: 55.679306
        lon: 11.274972
        start_date: 2019-12-01
        end_date: 2025-11-24

      Penmanshiel:
        lat: 55.903611
        lon: -2.291667
        start_date: 2016-01-01
        end_date: 2024-12-31

      Dundalk:
        lat: 53.98352
        lon: -6.391390
        start_date: 2006-01-01
        end_date: 2020-12-31

      Kelmarsh:
        lat: 52.401111
        lon: -0.942778
        start_date: 2016-01-01
        end_date: 2024-12-31


